apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brum
  namespace: brum
spec:
  ingresses:
    - https://brum.intern.dev.nav.no
  azure:
    application:
      enabled: true
    sidecar:
      enabled: true
      allowAllUsers: true
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki