apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: brum-api
  namespace: brum
  annotations:
    texas.nais.io/enabled: "true"
spec:
  ingresses:
    - https://brum-api.intern.dev.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
        - application: brum
  env:
  - name: BRUM_FRONTEND_URL
    value: "brum.intern.dev.nav.no"
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  observability:
    logging:
      destinations:
        - id: loki
