name: Automerge Dependabot PRs

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  automerge:
    permissions:
      contents: write # for dependency graph & sarif    
    runs-on: ubuntu-latest
    steps:
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@a9483f435ed797ba98bce09b50773dce3ba240e9
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: '3'
          blackout-periods: 'Sat,Sun,T17:00:00/T08:00:00,2025-07-18/2099-12-31'
