name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
jobs:
  test-build-deploy:
    permissions:
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96
      - name: Test & build
        run: ./gradlew test build
      - name: Build & push docker image + SBOM
        uses: nais/docker-build-push@1fae4798c79f4af4c3cdbd3fe65e51f8f3ba2368
        id: docker-push
        with:
          team: brum
          pull: true
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@ac638b010cf58a27ee6c972d7336334ccaf61c96
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@76071ef0d7ec797419534a183b498b4d6366cf37
        with:
          image-ref: '${{ steps.docker-push.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@ce28f5bb42b7a9f2c824e633a3f6ee835bab6858
        with:
          sarif_file: 'trivy.sarif'
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    needs: test-build-deploy
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@094c1d72a12b0314f34df671cc5d09c3838ab95d
        env:
          RESOURCE: .nais/nais.yaml
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.test-build-deploy.outputs.image }}
